In [39]:
import pandas as pd
home =2

In [40]:
df =pd.read_csv("50_Startups.csv")

df.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [41]:
x = df.drop('Profit',axis =1)
y = df['Profit']

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
train_x, test_x, train_y, test_y = train_test_split(x,y, test_size=0.2, random_state=56)

In [44]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [45]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()

linear_reg.fit(train_x, train_y)
train_predict = linear_reg.predict(train_x)
test_predict = linear_reg.predict(test_x)

In [46]:
mse_test = mean_squared_error(test_y, test_predict)
mae_test = mean_absolute_error(test_y, test_predict)
r2_test = r2_score(test_y, test_predict)

print('Mean Squared Error (MSE):', mse_test)
print('Mean Absolute Error (MAE):', mae_test)
print('R-squared (R^2) Score:', r2_test)

Mean Squared Error (MSE): 82625134.50350608
Mean Absolute Error (MAE): 7189.821723426683
R-squared (R^2) Score: 0.9450409080030587


In [47]:
from sklearn.tree import DecisionTreeRegressor

# Create a Decision Tree regressor
decision_tree_reg = DecisionTreeRegressor(random_state=56)

# Train the Decision Tree regressor
decision_tree_reg.fit(train_x, train_y)

# Make predictions on the training and test sets
train_predict_dt = decision_tree_reg.predict(train_x)
test_predict_dt = decision_tree_reg.predict(test_x)

In [48]:
mse_test_dt = mean_squared_error(test_y, test_predict_dt)
mae_test_dt = mean_absolute_error(test_y, test_predict_dt)
r2_test_dt = r2_score(test_y, test_predict_dt)

print('Mean Squared Error (MSE):', mse_test_dt)
print('Mean Absolute Error (MAE):', mae_test_dt)
print('R-squared (R^2) Score:', r2_test_dt)

Mean Squared Error (MSE): 107028360.39833996
Mean Absolute Error (MAE): 7955.639999999997
R-squared (R^2) Score: 0.9288088117403966


In [49]:
from sklearn.ensemble import GradientBoostingRegressor

# Create a Gradient Boosting regressor
gradient_boosting_reg = GradientBoostingRegressor(random_state=56)

# Train the Gradient Boosting regressor
gradient_boosting_reg.fit(train_x, train_y)

# Make predictions on the training and test sets
train_predict_gb = gradient_boosting_reg.predict(train_x)
test_predict_gb = gradient_boosting_reg.predict(test_x)


In [50]:
mse_test_gb = mean_squared_error(test_y, test_predict_gb)
mae_test_gb = mean_absolute_error(test_y, test_predict_gb)
r2_test_gb = r2_score(test_y, test_predict_gb)

print('Mean Squared Error (MSE):', mse_test_gb)
print('Mean Absolute Error (MAE):', mae_test_gb)
print('R-squared (R^2) Score:', r2_test_gb)

Mean Squared Error (MSE): 105722388.48894832
Mean Absolute Error (MAE): 8879.91096281686
R-squared (R^2) Score: 0.9296774945055742


In [51]:
from sklearn.neighbors import KNeighborsRegressor

# Create a KNN regressor
knn_reg = KNeighborsRegressor()

# Train the KNN regressor
knn_reg.fit(train_x, train_y)

# Make predictions on the training and test sets
train_predict_knn = knn_reg.predict(train_x)
test_predict_knn = knn_reg.predict(test_x)

In [52]:
mse_test_knn = mean_squared_error(test_y, test_predict_knn)
mae_test_knn = mean_absolute_error(test_y, test_predict_knn)
r2_test_knn = r2_score(test_y, test_predict_knn)

print('Mean Squared Error (MSE):', mse_test_knn)
print('Mean Absolute Error (MAE):', mae_test_knn)
print('R-squared (R^2) Score:', r2_test_knn)

Mean Squared Error (MSE): 152952768.1744823
Mean Absolute Error (MAE): 9746.939999999997
R-squared (R^2) Score: 0.8982616451059273


In [53]:
import numpy as np
X = np.array([[165349.20,136897.80,471784.10]])
X

array([[165349.2, 136897.8, 471784.1]])

In [54]:
y_preded_linear = linear_reg.predict(X)
y_preded_linear

c:\Users\omsar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([194018.93382483])

In [55]:
y_pred_knn=knn_reg.predict(X)
y_pred_knn
home =1

c:\Users\omsar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([179656.668])

In [56]:
from sklearn.ensemble import RandomForestRegressor

# Create a Gradient Boosting regressor
Random_forest_reg = RandomForestRegressor()

# Train the Gradient Boosting regressor
Random_forest_reg.fit(train_x, train_y)

# Make predictions on the training and test sets
train_predict_rf = Random_forest_reg.predict(train_x)
test_predict_rf = Random_forest_reg.predict(test_x)


In [57]:
mse_test_rf = mean_squared_error(test_y, test_predict_rf)
mae_test_rf = mean_absolute_error(test_y, test_predict_rf)
r2_test_rf = r2_score(test_y, test_predict_rf)

print('Mean Squared Error (MSE):', mse_test_rf)
print('Mean Absolute Error (MAE):', mae_test_rf)
print('R-squared (R^2) Score:', r2_test_rf)

Mean Squared Error (MSE): 129470337.21713409
Mean Absolute Error (MAE): 9334.805800000026
R-squared (R^2) Score: 0.9138812636524115
